import type { Metadata } from "next"
import Link from "next/link"
import { ChevronRight, HelpCircle } from "lucide-react"
import { Footer } from "@/components/footer"

export const metadata: Metadata = {
  title: "FAQ - Zaza Draft | Frequently Asked Questions",
  description:
    "Find answers to common questions about Zaza Draft, the AI-powered communication assistant for teachers. Learn about features, pricing, privacy, and more.",
  keywords: "Zaza Draft FAQ, teacher communication tool questions, AI assistant for teachers, parent email help",
}

export default function FAQPage() {
  const faqs = [
    {
      category: "Getting Started",
      questions: [
        {
          question: "What is Zaza Draft?",
          answer:
            "Zaza Draft is an AI-powered communication assistant that helps teachers write professional, empathetic parent emails in seconds while protecting their work-life boundaries. Our platform understands education context and generates ready-to-send communications for behavior concerns, progress updates, absence follow-ups, and more.",
        },
        {
          question: "How does Zaza Draft save teachers time?",
          answer:
            "Teachers save an average of 3+ hours per week by using Zaza Draft to generate drafts instead of writing from scratch. Our AI understands education context and creates ready-to-send communications in seconds, not minutes. Simply describe the situation, select a tone, and get a professional draft instantly.",
        },
        {
          question: "Who is Zaza Draft for?",
          answer:
            "Zaza Draft is designed for all teachers, teaching assistants, and education professionals who communicate with parents. It works for teachers of all subjects and grade levels, from Reception to Year 13, including primary teachers, secondary teachers, SEND teachers, and teaching assistants.",
        },
        {
          question: "Do I need technical skills to use Zaza Draft?",
          answer:
            "No technical skills are required. Zaza Draft is designed to be simple and intuitive. Just describe the situation in plain language, choose your preferred tone, and click generate. The AI handles the rest.",
        },
      ],
    },
    {
      category: "Features & Functionality",
      questions: [
        {
          question: "What types of communications can Zaza Draft help with?",
          answer:
            "Zaza Draft can help with all types of parent communications including behavior concerns, progress updates, absence follow-ups, homework reminders, positive feedback, meeting requests, permission slips, and general updates. Our AI understands the nuances of each communication type.",
        },
        {
          question: "Can I customize the tone of my messages?",
          answer:
            "Yes, Zaza Draft offers multiple tone options including professional, empathetic, direct, encouraging, and formal. You can select the tone that best fits your situation and relationship with the parent.",
        },
        {
          question: "Can I edit the generated drafts?",
          answer:
            "Absolutely. Every draft generated by Zaza Draft is fully editable. You can modify, add, or remove any content before sending. Think of it as a smart starting point that you can personalize.",
        },
        {
          question: "Does Zaza Draft work in multiple languages?",
          answer:
            "Currently, Zaza Draft is optimized for English communications. We're working on adding support for additional languages based on user demand.",
        },
        {
          question: "Can I save my favorite templates?",
          answer:
            "Yes, you can favorite any generated draft to save it as a template for future use. This is perfect for recurring communications like weekly updates or standard reminders.",
        },
        {
          question: "Does Zaza Draft integrate with my school's email system?",
          answer:
            "Zaza Draft generates text drafts that you can copy and paste into any email system. We're working on direct integrations with popular school management systems for future releases.",
        },
      ],
    },
    {
      category: "Privacy & Security",
      questions: [
        {
          question: "Is my data private and secure?",
          answer:
            "Yes, your privacy is our top priority. We never share your data with third parties, and all communications are encrypted. You own your drafts, and we don't use your content to train AI models.",
        },
        {
          question: "Does Zaza Draft store student information?",
          answer:
            "No, Zaza Draft does not store any student names or personal information. You describe situations in general terms, and the AI generates appropriate communications without requiring or storing sensitive student data.",
        },
        {
          question: "Is Zaza Draft GDPR compliant?",
          answer:
            "Yes, Zaza Draft is fully GDPR compliant. We follow strict data protection regulations and give you full control over your data. You can delete your account and all associated data at any time.",
        },
        {
          question: "Where is my data stored?",
          answer:
            "All data is stored securely in encrypted databases within the European Union, ensuring compliance with UK and EU data protection laws.",
        },
      ],
    },
    {
      category: "Pricing & Plans",
      questions: [
        {
          question: "How much does Zaza Draft cost?",
          answer:
            "Zaza Draft offers a free tier with 10 drafts per month, perfect for trying the service. Premium plans start at £9/month for unlimited drafts, priority support, and advanced features. We also offer school-wide licenses with volume discounts.",
        },
        {
          question: "Is there a free trial?",
          answer:
            "Yes, you can start with our free tier that includes 10 drafts per month with no credit card required. This lets you experience the full power of Zaza Draft before committing to a paid plan.",
        },
        {
          question: "Can I cancel my subscription anytime?",
          answer:
            "Yes, you can cancel your subscription at any time with no penalties or fees. Your access will continue until the end of your current billing period.",
        },
        {
          question: "Do you offer school or district licenses?",
          answer:
            "Yes, we offer special pricing for schools and districts. Contact us at hello@zazatechnologies.com for volume pricing and custom solutions for your institution.",
        },
        {
          question: "What payment methods do you accept?",
          answer:
            "We accept all major credit cards (Visa, Mastercard, American Express) and debit cards. School purchase orders are also accepted for institutional licenses.",
        },
      ],
    },
    {
      category: "Support & Training",
      questions: [
        {
          question: "How do I get started with Zaza Draft?",
          answer:
            "Getting started is simple: sign up for a free account, describe your first communication situation, select a tone, and click generate. You'll have a professional draft in seconds. No training or setup required.",
        },
        {
          question: "Do you offer training for teachers?",
          answer:
            "Yes, we provide free onboarding resources including video tutorials, best practice guides, and example templates. For school licenses, we offer live training sessions for your staff.",
        },
        {
          question: "What if I need help or have questions?",
          answer:
            "We offer email support at support@zazatechnologies.com with responses typically within 24 hours. Premium users get priority support with faster response times.",
        },
        {
          question: "Can I request new features?",
          answer:
            "We love hearing from our users. Send feature requests to hello@zazatechnologies.com, and we'll consider them for future updates.",
        },
      ],
    },
    {
      category: "Specific Use Cases",
      questions: [
        {
          question: "Is Zaza Draft suitable for primary teachers?",
          answer:
            "Yes, Zaza Draft is perfect for primary teachers. Our AI understands the unique communication needs of primary education, including parent partnerships, early years development, and age-appropriate language for young learners.",
        },
        {
          question: "Can secondary teachers use Zaza Draft?",
          answer:
            "Absolutely. Zaza Draft works excellently for secondary teachers who need to communicate about subject-specific concerns, exam preparation, behavior management, and academic progress across multiple classes.",
        },
        {
          question: "Does Zaza Draft work for SEND teachers?",
          answer:
            "Yes, Zaza Draft is valuable for SEND teachers who need to write sensitive, empathetic communications about individual learning plans, accommodations, progress updates, and support strategies.",
        },
        {
          question: "Can teaching assistants use Zaza Draft?",
          answer:
            "Yes, teaching assistants can use Zaza Draft to help draft communications under teacher supervision, prepare progress notes, and document student interactions professionally.",
        },
        {
          question: "Is Zaza Draft useful for behavior concerns?",
          answer:
            "Yes, behavior concerns are one of the most common use cases. Zaza Draft helps you write balanced, professional communications that address concerns while maintaining positive parent relationships and suggesting constructive solutions.",
        },
        {
          question: "Can I use Zaza Draft for positive feedback?",
          answer:
            "Zaza Draft excels at generating positive, encouraging messages to celebrate student achievements, improvements, and good behavior. Positive communications are just as important as addressing concerns.",
        },
      ],
    },
    {
      category: "Technical Questions",
      questions: [
        {
          question: "What devices can I use Zaza Draft on?",
          answer:
            "Zaza Draft works on any device with a web browser including desktop computers, laptops, tablets, and smartphones. The interface is fully responsive and optimized for all screen sizes.",
        },
        {
          question: "Do I need to install any software?",
          answer:
            "No installation required. Zaza Draft is a web-based application that runs entirely in your browser. Just visit the website, log in, and start creating drafts.",
        },
        {
          question: "Does Zaza Draft work offline?",
          answer:
            "No, Zaza Draft requires an internet connection to generate drafts using AI. However, you can copy generated drafts to use offline later.",
        },
        {
          question: "What browsers are supported?",
          answer:
            "Zaza Draft works on all modern browsers including Chrome, Firefox, Safari, and Edge. We recommend using the latest version of your preferred browser for the best experience.",
        },
      ],
    },
    {
      category: "Comparison Questions",
      questions: [
        {
          question: "How is Zaza Draft different from ChatGPT?",
          answer:
            "Unlike ChatGPT, Zaza Draft is specifically designed for teacher-parent communications with education-specific templates, tone options, and context understanding. You don't need to craft prompts or explain education terminology - Zaza Draft already knows the context.",
        },
        {
          question: "How does Zaza Draft compare to Grammarly?",
          answer:
            "While Grammarly helps you edit existing text, Zaza Draft generates complete drafts from scratch. It's not just about grammar - it's about creating professional, empathetic communications that save you time and protect your boundaries.",
        },
        {
          question: "Why not just use my school's email templates?",
          answer:
            "Generic school templates lack personalization and context. Zaza Draft generates customized communications for your specific situation while maintaining professionalism and empathy. Every draft is unique to your needs.",
        },
      ],
    },
  ]

  return (
    <>
      {/* FAQ Schema for AEO */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: faqs.flatMap((category) =>
              category.questions.map((faq) => ({
                "@type": "Question",
                name: faq.question,
                acceptedAnswer: {
                  "@type": "Answer",
                  text: faq.answer,
                },
              })),
            ),
          }),
        }}
      />

      <div className="min-h-screen bg-gradient-to-b from-white to-purple-50/30 dark:from-gray-950 dark:to-gray-900">
        {/* Header */}
        <header className="border-b border-gray-200 dark:border-gray-800 bg-white/80 dark:bg-gray-950/80 backdrop-blur-sm sticky top-0 z-10">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
            <nav className="flex items-center justify-between">
              <Link
                href="/"
                className="text-sm text-gray-600 dark:text-gray-400 hover:text-purple-600 dark:hover:text-purple-400 transition-colors flex items-center gap-1"
              >
                <ChevronRight className="w-4 h-4 rotate-180" />
                Back to Home
              </Link>
            </nav>
          </div>
        </header>

        {/* Main Content */}
        <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
          {/* Page Header */}
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-16 h-16 bg-purple-100 dark:bg-purple-900/30 rounded-2xl mb-6">
              <HelpCircle className="w-8 h-8 text-purple-600 dark:text-purple-400" />
            </div>
            <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 dark:text-white mb-4">
              Frequently Asked Questions
            </h1>
            <p className="text-lg text-gray-600 dark:text-gray-400 max-w-2xl mx-auto leading-relaxed">
              Find answers to common questions about Zaza Draft, the AI-powered communication assistant for teachers.
            </p>
          </div>

          {/* FAQ Categories */}
          <div className="space-y-12">
            {faqs.map((category, categoryIndex) => (
              <section
                key={categoryIndex}
                className="scroll-mt-20"
                id={category.category.toLowerCase().replace(/\s+/g, "-")}
              >
                <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6 pb-2 border-b-2 border-purple-200 dark:border-purple-800">
                  {category.category}
                </h2>
                <div className="space-y-8">
                  {category.questions.map((faq, faqIndex) => (
                    <article
                      key={faqIndex}
                      className="bg-white dark:bg-gray-900 rounded-xl p-6 shadow-sm border border-gray-200 dark:border-gray-800 hover:shadow-md transition-shadow"
                    >
                      <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-3 leading-relaxed">
                        {faq.question}
                      </h3>
                      <p className="text-base text-gray-700 dark:text-gray-300 leading-relaxed">{faq.answer}</p>
                    </article>
                  ))}
                </div>
              </section>
            ))}
          </div>

          {/* CTA Section */}
          <div className="mt-16 text-center bg-gradient-to-br from-purple-50 to-pink-50 dark:from-purple-900/20 dark:to-pink-900/20 rounded-2xl p-8 border border-purple-200 dark:border-purple-800">
            <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-3">Still have questions?</h2>
            <p className="text-gray-600 dark:text-gray-400 mb-6 leading-relaxed">
              We're here to help! Contact our support team or try Zaza Draft for free.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                href="/"
                className="inline-flex items-center justify-center px-6 py-3 bg-gradient-to-r from-purple-600 to-purple-700 text-white font-medium rounded-lg hover:from-purple-700 hover:to-purple-800 transition-all shadow-lg hover:shadow-xl"
              >
                Try Zaza Draft Free
              </Link>
              <Link
                href="/contact"
                className="inline-flex items-center justify-center px-6 py-3 bg-white dark:bg-gray-800 text-gray-900 dark:text-white font-medium rounded-lg border-2 border-gray-300 dark:border-gray-700 hover:border-purple-600 dark:hover:border-purple-400 transition-colors"
              >
                Contact Support
              </Link>
            </div>
          </div>
        </main>

        <Footer />
      </div>
    </>
  )
}
